// Generated by ts-to-zod
import { z } from 'zod';

export const propertyAddressSchema = z.object({
	property_address_street: z.string(),
	property_address_suburb: z.string(),
	property_address_postcode: z.string().nullable()
});

export const userPostalAddressSchema = z
	.object({
		postal_address_street: z.string(),
		postal_address_suburb: z.string(),
		postal_address_postcode: z.string().nullable()
	})
	.nullable();

export const propertyAgentSchema = z
	.object({
		agent_name: z.string().nullable(),
		agent_mobile: z.string().nullable(),
		agent_phone: z.string().nullable()
	})
	.nullable();

export const kyngAreaSchema = z.object({
	kyng: z.string()
});

export const kyngAreasSchema = z.array(kyngAreaSchema);

export const communityAreaSchema = z.object({
	community: z.string()
});

export const communityAreasSchema = z.array(communityAreaSchema);

export const propertyProfileSchema = z.object({
	fire_fighting_resources: z.array(z.number()).nullable(),
	fire_hazard_reduction: z.array(z.number()).nullable(),
	have_stortz: z.string().nullable(),
	land_adjacent_hazard: z.string().nullable(),
	live_stock_present: z.boolean().nullable(),
	live_stock_safe_area: z.string().nullable(),
	mobile_reception: z.number().nullable(),
	number_birds: z.number().nullable(),
	number_cats: z.number().nullable(),
	number_dogs: z.number().nullable(),
	number_other_pets: z.number().nullable(),
	other_essential_assets: z.string().nullable(),
	other_hazards: z.string().nullable(),
	other_site_hazards: z.string().nullable(),
	phone: z.string().nullable(),
	property_address_postcode: z.string().nullable(),
	property_address_street: z.string(),
	property_address_suburb: z.string(),
	property_rented: z.boolean().nullable(),
	property_agent: propertyAgentSchema.nullable(),
	residents0_18: z.number().nullable(),
	residents19_50: z.number().nullable(),
	residents51_70: z.number().nullable(),
	residents71_: z.number().nullable(),
	share_livestock_safe_area: z.string().nullable(),
	sign_posted: z.boolean().nullable(),
	site_hazards: z.array(z.number()).nullable(),
	static_water_available: z.array(z.number()).nullable(),
	stortz_size: z.number().nullable(),
	truck_access: z.number().nullable(),
	truck_access_other_information: z.string().nullable(),
	vulnerable_residents: z.boolean().nullable(),
	id: z.string(),
	kyng_areas: kyngAreasSchema.nullable(),
	community_areas: communityAreasSchema.nullable()
});

export const bcycaCommunityProfileSchema = z
	.object({
		bcyca_profile_id: z.string(),
		community_meeting_choices: z.array(z.number()).nullable(),
		community_workshop_choices: z.array(z.number()).nullable(),
		information_sheet_choices: z.array(z.number()).nullable(),
		other_community_meeting: z.string().nullable(),
		other_community_workshop: z.string().nullable(),
		other_information_sheet: z.string().nullable(),
		stay_in_touch_choices: z.array(z.number()).nullable(),
		will_run_community_workshops: z.string().nullable()
	})
	.nullable();

export const tinoneeCommunityProfileSchema = z
	.object({
		tinonee_profile_id: z.string(),
		community_meeting_choices: z.array(z.number()).nullable(),
		community_workshop_choices: z.array(z.number()).nullable(),
		information_sheet_choices: z.array(z.number()).nullable(),
		other_community_meeting: z.string().nullable(),
		other_community_workshop: z.string().nullable(),
		other_information_sheet: z.string().nullable(),
		stay_in_touch_choices: z.array(z.number()).nullable(),
		will_run_community_workshops: z.string().nullable()
	})
	.nullable();

export const mondrookCommunityProfileSchema = z
	.object({
		mondrook_profile_id: z.string(),
		community_meeting_choices: z.array(z.number()).nullable(),
		community_workshop_choices: z.array(z.number()).nullable(),
		information_sheet_choices: z.array(z.number()).nullable(),
		other_community_meeting: z.string().nullable(),
		other_community_workshop: z.string().nullable(),
		other_information_sheet: z.string().nullable(),
		stay_in_touch_choices: z.array(z.number()).nullable(),
		will_run_community_workshops: z.string().nullable()
	})
	.nullable();

export const externalCommunityProfileSchema = z
	.object({
		external_profile_id: z.string(),
		community_meeting_choices: z.array(z.number()).nullable(),
		community_workshop_choices: z.array(z.number()).nullable(),
		information_sheet_choices: z.array(z.number()).nullable(),
		other_community_meeting: z.string().nullable(),
		other_community_workshop: z.string().nullable(),
		other_information_sheet: z.string().nullable(),
		stay_in_touch_choices: z.array(z.number()).nullable(),
		will_run_community_workshops: z.string().nullable()
	})
	.nullable();

export const userProfileSchema = z.object({
	family_name: z.string().nullable(),
	fire_fighting_experience: z.number().nullable(),
	fire_trauma: z.boolean().nullable(),
	first_name: z.string().nullable(),
	mobile: z.string().nullable(),
	other_comments: z.string().nullable(),
	plan_to_leave_before_fire: z.number().nullable(),
	plan_to_leave_before_flood: z.number().nullable(),
	residency_profile: z.number().nullable(),
	rfs_survival_plan: z.string().nullable(),
	stay_in_touch_choices: z.array(z.number()).nullable(),
	user_postal_address: userPostalAddressSchema.nullable(),
	property_profile: z.array(propertyProfileSchema),
	community_bcyca_profile: bcycaCommunityProfileSchema.nullable(),
	community_tinonee_profile: tinoneeCommunityProfileSchema.nullable(),
	community_mondrook_profile: mondrookCommunityProfileSchema.nullable(),
	community_external_profile: externalCommunityProfileSchema.nullable()
});

export const personalProfileFormDataSchema = userProfileSchema.omit({ property_profile: true }).and(
	z.object({
		property_profile: propertyProfileSchema
	})
);
